package com.everli.designsystem.playground.icon

import androidx.compose.runtime.Composable
import androidx.compose.ui.graphics.painter.Painter
import com.everli.designsystem.core.constants.EverliIcons

data class IconModel(
  val name: String,
  val icon: Painter,
)

@Composable
fun iconModels() = listOf(
  IconModel(name = "ico-action-more", icon = EverliIcons.ActionMore),
  IconModel(name = "ico-add", icon = EverliIcons.Add),
  IconModel(name = "ico-add-circle", icon = EverliIcons.AddCircle),
  IconModel(name = "ico-alert", icon = EverliIcons.Alert),
  IconModel(name = "ico-arrow-left", icon = EverliIcons.ArrowLeft),
  IconModel(name = "ico-arrow-left-circle", icon = EverliIcons.ArrowLeftCircle),
  IconModel(name = "ico-arrow-right", icon = EverliIcons.ArrowRight),
  IconModel(name = "ico-ask-questions", icon = EverliIcons.AskQuestion),
  IconModel(name = "ico-cart", icon = EverliIcons.Cart),
  IconModel(name = "ico-cash", icon = EverliIcons.Cash),
  IconModel(name = "ico-categories", icon = EverliIcons.Categories),
  IconModel(name = "ico-chat", icon = EverliIcons.Chat),
  IconModel(name = "ico-checkmark", icon = EverliIcons.Checkmark),
  IconModel(name = "ico-checkmark-circle-filled", icon = EverliIcons.CheckmarkCircleFilled),
  IconModel(name = "ico-checkmark-circle-outline", icon = EverliIcons.CheckmarkCircleOutline),
  IconModel(name = "ico-chevron-down", icon = EverliIcons.ChevronDown),
  IconModel(name = "ico-chevron-left", icon = EverliIcons.ChevronLeft),
  IconModel(name = "ico-chevron-right", icon = EverliIcons.ChevronRight),
  IconModel(name = "ico-chevron-top", icon = EverliIcons.ChevronTop),
  IconModel(name = "ico-chevron-top", icon = EverliIcons.ChevronTop),
  IconModel(name = "ico-clock", icon = EverliIcons.Clock),
  IconModel(name = "ico-close", icon = EverliIcons.Close),
  IconModel(name = "ico-contract", icon = EverliIcons.Contract),
  IconModel(name = "ico-cookie", icon = EverliIcons.Cookie),
  IconModel(name = "ico-credit-card", icon = EverliIcons.CreditCard),
  IconModel(name = "ico-delete", icon = EverliIcons.Delete),
  IconModel(name = "ico-download", icon = EverliIcons.Download),
  IconModel(name = "ico-docs", icon = EverliIcons.Docs),
  IconModel(name = "ico-edit", icon = EverliIcons.Edit),
  IconModel(name = "ico-email", icon = EverliIcons.Email),
  IconModel(name = "ico-empty", icon = EverliIcons.Empty),
  IconModel(name = "ico-error", icon = EverliIcons.Error),
  IconModel(name = "ico-favorite-filled", icon = EverliIcons.FavoriteFilled),
  IconModel(name = "ico-favorite-outline", icon = EverliIcons.FavoriteOutline),
  IconModel(name = "ico-filters", icon = EverliIcons.Filters),
  IconModel(name = "ico-filters-multiple", icon = EverliIcons.FiltersMultiple),
  IconModel(name = "ico-flash", icon = EverliIcons.Flash),
  IconModel(name = "ico-flash-circle", icon = EverliIcons.FlashCircle),
  IconModel(name = "ico-forward", icon = EverliIcons.Forward),
  IconModel(name = "ico-gift", icon = EverliIcons.Gift),
  IconModel(name = "ico-gift-card", icon = EverliIcons.GiftCard),
  IconModel(name = "ico-gps", icon = EverliIcons.Gps),
  IconModel(name = "ico-help", icon = EverliIcons.Help),
  IconModel(name = "ico-home", icon = EverliIcons.Home),
  IconModel(name = "ico-info", icon = EverliIcons.Info),
  IconModel(name = "ico-invoice", icon = EverliIcons.Invoice),
  IconModel(name = "ico-menu", icon = EverliIcons.Menu),
  IconModel(name = "ico-note-product", icon = EverliIcons.NoteProduct),
  IconModel(name = "ico-note-shopper", icon = EverliIcons.NoteShopper),
  IconModel(name = "ico-notifications", icon = EverliIcons.Notifications),
  IconModel(name = "ico-padlock", icon = EverliIcons.Padlock),
  IconModel(name = "ico-pos", icon = EverliIcons.Pos),
  IconModel(name = "ico-position-marker-filled", icon = EverliIcons.PositionMarkerFilled),
  IconModel(name = "ico-position-marker-outline", icon = EverliIcons.PositionMarkerOutline),
  IconModel(name = "ico-question-mark", icon = EverliIcons.QuestionMark),
  IconModel(name = "ico-remove", icon = EverliIcons.Remove),
  IconModel(name = "ico-replacements", icon = EverliIcons.Replacements),
  IconModel(name = "ico-save", icon = EverliIcons.Save),
  IconModel(name = "ico-search", icon = EverliIcons.Search),
  IconModel(name = "ico-settings", icon = EverliIcons.Settings),
  IconModel(name = "ico-shield-consents", icon = EverliIcons.ShieldConsents),
  IconModel(name = "ico-shield-privacy", icon = EverliIcons.ShieldPrivacy),
  IconModel(name = "ico-shopping-list", icon = EverliIcons.ShoppingList),
  IconModel(name = "ico-user", icon = EverliIcons.User),
  IconModel(name = "ico-user-verified", icon = EverliIcons.UserVerified),
  IconModel(name = "ico-waller", icon = EverliIcons.Wallet),
  IconModel(name = "ico-zoom", icon = EverliIcons.Zoom),
)
