package com.everli.designsystem.core.constants

import com.everli.designsystem.utilities.extensions.empty

enum class EverliResource(val designName: String) {

  NONE(designName = String.empty),
  ICO_ADD(designName = "ico-add"),
  ICO_ADD_CIRCLE(designName = "ico-add-circle"),
  ICO_ALERT(designName = "ico-alert"),
  ICO_ANNOUNCEMENT(designName = "ico-announcement"),
  ICO_ARROW_DOWN_CIRCLE(designName = "ico-arrow-down-circle"),
  ICO_ARROW_EXTERNAL(designName = "ico-arrow-external"),
  ICO_ARROW_LEFT(designName = "ico-arrow-left"),
  ICO_ARROW_LEFT_CIRCLE(designName = "ico-arrow-left-circle"),
  ICO_ARROW_RIGHT(designName = "ico-arrow-right"),
  ICO_ARROW_RIGHT_CIRCLE(designName = "ico-arrow-right-circle"),
  ICO_ARROW_TOP(designName = "ico-arrow-top"),
  ICO_ARROW_TOP_CIRCLE(designName = "ico-arrow-top-circle"),
  ICO_ASK_QUESTION(designName = "ico-ask-question"),
  ICO_BASKET(designName = "ico-basket"),
  ICO_BASKET_CIRCLE(designName = "ico-basket-circle"),
  ICO_CASH(designName = "ico-cash"),
  ICO_CASH_OUT(designName = "ico-cash-out"),
  ICO_CASHBACK(designName = "ico-cashback"),
  ICO_CASHBACK_PLUS(designName = "ico-cashback-plus"),
  ICO_CATEGORIES(designName = "ico-categories"),
  ICO_CHAT(designName = "ico-chat"),
  ICO_CHECK(designName = "ico-check"),
  ICO_CHECK_CIRCLE_FILLED(designName = "ico-check-circle-filled"),
  ICO_CHECK_CIRCLE_OUTLINE(designName = "ico-check-circle-outline"),
  ICO_CHEVRON_DOWN(designName = "ico-chevron-down"),
  ICO_CHEVRON_LEFT(designName = "ico-chevron-left"),
  ICO_CHEVRON_RIGHT(designName = "ico-chevron-right"),
  ICO_CHEVRON_TOP(designName = "ico-chevron-top"),
  ICO_CLOCK(designName = "ico-clock"),
  ICO_CLOCK_FILLED(designName = "ico-clock-filled"),
  ICO_CONTRACT(designName = "ico-contract"),
  ICO_COOKIE(designName = "ico-cookie"),
  ICO_CREDIT_CARD(designName = "ico-credit-card"),
  ICO_DELETE(designName = "ico-delete"),
  ICO_DELIVERY(designName = "ico-delivery"),
  ICO_DOCS(designName = "ico-docs"),
  ICO_DOLLAR(designName = "ico-dollar"),
  ICO_DOWNLOAD(designName = "ico-download"),
  ICO_ECO(designName = "ico-eco"),
  ICO_EDIT(designName = "ico-edit"),
  ICO_EMAIL(designName = "ico-email"),
  ICO_EMPTY(designName = "ico-empty"),
  ICO_EURO(designName = "ico-euro"),
  ICO_EYE_HYDE(designName = "ico-eye-hyde"),
  ICO_EYE_SHOW(designName = "ico-eye-show"),
  ICO_FAVORITE_FILLED(designName = "ico-favorite-filled"),
  ICO_FAVORITE_OUTLINE(designName = "ico-favorite-outline"),
  ICO_FILTERS(designName = "ico-filters"),
  ICO_FILTERS_MULTIPLE(designName = "ico-filters-multiple"),
  ICO_FLASH(designName = "ico-flash"),
  ICO_FLASH_CIRCLE(designName = "ico-flash-circle"),
  ICO_FORWARD(designName = "ico-forward"),
  ICO_GIFT(designName = "ico-gift"),
  ICO_GIFT_CARD(designName = "ico-gift-card"),
  ICO_GPS(designName = "ico-gps"),
  ICO_HELP(designName = "ico-help"),
  ICO_HOME(designName = "ico-home"),
  ICO_INFO_CIRCLE_FILLED(designName = "ico-info-circle-filled"),
  ICO_INFO_CIRCLE_OUTLINE(designName = "ico-info-circle-outline"),
  ICO_INVOICE(designName = "ico-invoice"),
  ICO_LABEL(designName = "ico-label"),
  ICO_LINK(designName = "ico-link"),
  ICO_MENU(designName = "ico-menu"),
  ICO_MORE(designName = "ico-more"),
  ICO_NOTE(designName = "ico-note"),
  ICO_NOTIFICATIONS(designName = "ico-notifications"),
  ICO_PADLOCK(designName = "ico-padlock"),
  ICO_PADLOCK_CIRCLE(designName = "ico-padlock-circle"),
  ICO_POS(designName = "ico-pos"),
  ICO_POSITION_MARK_FILLED(designName = "ico-position-mark-filled"),
  ICO_POSITION_MARK_OUTLINE(designName = "ico-position-mark-outline"),
  ICO_QUESTION_CIRCLE_FILLED(designName = "ico-question-circle-filled"),
  ICO_QUESTION_CIRCLE_OUTILNE(designName = "ico-question-circle-outilne"),
  ICO_REFUND(designName = "ico-refund"),
  ICO_REMOVE(designName = "ico-remove"),
  ICO_REPLACEMENTS(designName = "ico-replacements"),
  ICO_ROCKET(designName = "ico-rocket"),
  ICO_SATISFACTION(designName = "ico-satisfaction"),
  ICO_SAVE(designName = "ico-save"),
  ICO_SEARCH(designName = "ico-search"),
  ICO_SETTINGS(designName = "ico-settings"),
  ICO_SHIELD_CONSENTS(designName = "ico-shield-consents"),
  ICO_SHIELD_PRIVACY(designName = "ico-shield-privacy"),
  ICO_SHOPPING_LIST(designName = "ico-shopping-list"),
  ICO_STAR(designName = "ico-star"),
  ICO_SUPPLY_ARMCHAIR(designName = "ico-supply-armchair"),
  ICO_SUPPLY_BONUS_FIRE(designName = "ico-supply-bonus-fire"),
  ICO_SUPPLY_BONUS_STAR(designName = "ico-supply-bonus-star"),
  ICO_SUPPLY_CALENDAR(designName = "ico-supply-calendar"),
  ICO_SUPPLY_CART(designName = "ico-supply-cart"),
  ICO_SUPPLY_MATERNITY(designName = "ico-supply-maternity"),
  ICO_SUPPLY_QUANTITY(designName = "ico-supply-quantity"),
  ICO_SUPPLY_REPLACEMENT(designName = "ico-supply-replacement"),
  ICO_SUPPLY_SCOOTER(designName = "ico-supply-scooter"),
  ICO_SUPPLY_SICKNESS(designName = "ico-supply-sickness"),
  ICO_SUPPLY_STATS(designName = "ico-supply-stats"),
  ICO_USER(designName = "ico-user"),
  ICO_USER_VERIFIED(designName = "ico-user-verified"),
  ICO_WALLET(designName = "ico-wallet"),
  ICO_WRITE(designName = "ico-write"),
  ICO_X(designName = "ico-x"),
  ICO_X_CIRCLE_FILLED(designName = "ico-x-circle-filled"),
  ICO_X_CIRCLE_OUTLINE(designName = "ico-x-circle-outline"),
  ICO_ZOOM(designName = "ico-zoom"),
  ICO_MENU_CATEGORIES(designName = "ico-menu-categories"),
  ICO_DEALS(designName = "ico-deals"),
  ICO_QUICK_SHOPPING(designName = "ico-quick-shopping"),
  LOGO_APPLE(designName = "logo-apple"),
  LOGO_APPLE_MAPS_APP(designName = "logo-apple-maps-app"),
  LOGO_EVERLI_APP(designName = "logo-everli-app"),
  LOGO_EVERLI_HAND(designName = "logo-everli-hand"),
  LOGO_EVERLI_HORIZONTAL(designName = "logo-everli-horizontal"),
  LOGO_EVERLI_PLUS_HORIZONTAL(designName = "logo-everli-plus-horizontal"),
  LOGO_EVERLI_VERTICAL(designName = "logo-everli-vertical"),
  LOGO_FACEBOOK(designName = "logo-facebook"),
  LOGO_GOOGLE(designName = "logo-google"),
  LOGO_GOOGLE_MAPS_APP(designName = "logo-google-maps-app"),
  LOGO_INSTAGRAM(designName = "logo-instagram"),
  LOGO_PAYMENT_AMEX(designName = "logo-payment-amex"),
  LOGO_PAYMENT_APPLE_PAY(designName = "logo-payment-apple-pay"),
  LOGO_PAYMENT_BLIK(designName = "logo-payment-blik"),
  LOGO_PAYMENT_GOOGLE_PAY(designName = "logo-payment-google-pay"),
  LOGO_PAYMENT_MASTERCARD(designName = "logo-payment-mastercard"),
  LOGO_PAYMENT_PAYPAL(designName = "logo-payment-paypal"),
  LOGO_PAYMENT_VISA(designName = "logo-payment-visa"),
  LOGO_PWRD_BY_GOOGLE(designName = "logo-pwrd-by-google"),
  LOGO_TWITTER(designName = "logo-twitter"),
  LOGO_WAZE(designName = "logo-waze"),
  LOGO_EDENRED(designName = "logo-edenred");

  companion object {

    /**
     * Convert a resource name as string to a [EverliResource]
     * Can be used only for design system based resources
     * If the conversion fails, [fallback] will be returned
     * If [fallback] is not provided, [NONE] will be returned
     *
     * @param name name of the resource e.g. "ico-basket"
     * @param fallback used in case the conversion fails, default value [NONE]
     * @return [EverliResource] for given [name] or [fallback]
     */
    fun fromString(name: String, fallback: EverliResource = NONE): EverliResource {
      return values().associateBy(EverliResource::designName)[name] ?: fallback
    }

  }

  override fun toString(): String = designName

}
